// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_settings: {
        Row: {
          id: boolean;
          monthly_spend_cap_usd: number;
          sweep_spend_cap_usd: number;
          sweeps_enabled: boolean;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          monthly_spend_cap_usd?: number;
          sweep_spend_cap_usd?: number;
          sweeps_enabled?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          monthly_spend_cap_usd?: number;
          sweep_spend_cap_usd?: number;
          sweeps_enabled?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      briefs: {
        Row: {
          id: string;
          title: string;
          period: string;
          objective_scope: string;
          content_md: string;
          pattern_ids: string[];
          model: string | null;
          prompt_version: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          period: string;
          objective_scope: string;
          content_md: string;
          pattern_ids?: string[];
          model?: string | null;
          prompt_version?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          period?: string;
          objective_scope?: string;
          content_md?: string;
          pattern_ids?: string[];
          model?: string | null;
          prompt_version?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      classifications: {
        Row: {
          id: string;
          item_id: string;
          video_hash: string | null;
          model: string;
          prompt_version: string;
          vision_version: string;
          labels_json: Json;
          evidence_json: Json;
          confidence: number | null;
          needs_review: boolean;
          corrections_json: Json;
          reviewed_by: string | null;
          reviewed_at: string | null;
          input_tokens: number | null;
          output_tokens: number | null;
          cost_usd: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          video_hash?: string | null;
          model: string;
          prompt_version: string;
          vision_version: string;
          labels_json: Json;
          evidence_json?: Json;
          confidence?: number | null;
          needs_review?: boolean;
          corrections_json?: Json;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          cost_usd?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          video_hash?: string | null;
          model?: string;
          prompt_version?: string;
          vision_version?: string;
          labels_json?: Json;
          evidence_json?: Json;
          confidence?: number | null;
          needs_review?: boolean;
          corrections_json?: Json;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          cost_usd?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'classifications_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
        ];
      };
      items: {
        Row: {
          id: string;
          source: string;
          source_url: string;
          external_id: string;
          advertiser: string | null;
          account_handle: string | null;
          region: string | null;
          industry: string | null;
          objective_source: string | null;
          posted_at: string | null;
          collected_at: string;
          duration_s: number | null;
          thumbnail_url: string | null;
          raw_json: Json;
        };
        Insert: {
          id?: string;
          source: string;
          source_url: string;
          external_id: string;
          advertiser?: string | null;
          account_handle?: string | null;
          region?: string | null;
          industry?: string | null;
          objective_source?: string | null;
          posted_at?: string | null;
          collected_at?: string;
          duration_s?: number | null;
          thumbnail_url?: string | null;
          raw_json?: Json;
        };
        Update: {
          id?: string;
          source?: string;
          source_url?: string;
          external_id?: string;
          advertiser?: string | null;
          account_handle?: string | null;
          region?: string | null;
          industry?: string | null;
          objective_source?: string | null;
          posted_at?: string | null;
          collected_at?: string;
          duration_s?: number | null;
          thumbnail_url?: string | null;
          raw_json?: Json;
        };
        Relationships: [];
      };
      media: {
        Row: {
          item_id: string;
          video_hash: string | null;
          width: number | null;
          height: number | null;
          scene_cuts: number[] | null;
          audio_type: string | null;
          transcript: string | null;
          transcript_lang: string | null;
          transcript_segments: Json | null;
          frames_json: Json | null;
          ocr_text: string | null;
          vision_model: string | null;
          vision_version: string | null;
          keyframe_paths: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          item_id: string;
          video_hash?: string | null;
          width?: number | null;
          height?: number | null;
          scene_cuts?: number[] | null;
          audio_type?: string | null;
          transcript?: string | null;
          transcript_lang?: string | null;
          transcript_segments?: Json | null;
          frames_json?: Json | null;
          ocr_text?: string | null;
          vision_model?: string | null;
          vision_version?: string | null;
          keyframe_paths?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          item_id?: string;
          video_hash?: string | null;
          width?: number | null;
          height?: number | null;
          scene_cuts?: number[] | null;
          audio_type?: string | null;
          transcript?: string | null;
          transcript_lang?: string | null;
          transcript_segments?: Json | null;
          frames_json?: Json | null;
          ocr_text?: string | null;
          vision_model?: string | null;
          vision_version?: string | null;
          keyframe_paths?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'media_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: true;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
        ];
      };
      metrics: {
        Row: {
          id: number;
          item_id: string;
          metric_name: string;
          value: number | null;
          value_text: string | null;
          unit: string | null;
          captured_at: string;
        };
        Insert: {
          id?: never;
          item_id: string;
          metric_name: string;
          value?: number | null;
          value_text?: string | null;
          unit?: string | null;
          captured_at?: string;
        };
        Update: {
          id?: never;
          item_id?: string;
          metric_name?: string;
          value?: number | null;
          value_text?: string | null;
          unit?: string | null;
          captured_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'metrics_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
        ];
      };
      patterns: {
        Row: {
          id: string;
          period: string;
          objective: string;
          region: string | null;
          label_combo: Json;
          direction: string;
          lift: number;
          share_top: number | null;
          share_all: number | null;
          top_count: number;
          cohort_count: number;
          advertiser_count: number;
          sources: string[];
          confidence: string | null;
          example_ids: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          period: string;
          objective: string;
          region?: string | null;
          label_combo: Json;
          direction: string;
          lift: number;
          share_top?: number | null;
          share_all?: number | null;
          top_count: number;
          cohort_count: number;
          advertiser_count: number;
          sources?: string[];
          confidence?: string | null;
          example_ids?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          period?: string;
          objective?: string;
          region?: string | null;
          label_combo?: Json;
          direction?: string;
          lift?: number;
          share_top?: number | null;
          share_all?: number | null;
          top_count?: number;
          cohort_count?: number;
          advertiser_count?: number;
          sources?: string[];
          confidence?: string | null;
          example_ids?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      run_items: {
        Row: {
          run_id: string;
          item_id: string;
          position: number;
          stage: string;
          status: string;
          attempts: number;
          error: string | null;
          stage_log: Json;
          cost_usd: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          run_id: string;
          item_id: string;
          position: number;
          stage?: string;
          status?: string;
          attempts?: number;
          error?: string | null;
          stage_log?: Json;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          run_id?: string;
          item_id?: string;
          position?: number;
          stage?: string;
          status?: string;
          attempts?: number;
          error?: string | null;
          stage_log?: Json;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'run_items_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'run_items_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'runs';
            referencedColumns: ['id'];
          },
        ];
      };
      runs: {
        Row: {
          id: string;
          source: string;
          watchlist_id: string | null;
          status: string;
          items_requested: number;
          items_done: number;
          items_failed: number;
          cost_estimate_usd: number | null;
          spend_cap_usd: number;
          cost_actual_usd: number;
          pause_requested: boolean;
          worker_run_id: string | null;
          error: string | null;
          created_by: string | null;
          created_at: string;
          started_at: string | null;
          finished_at: string | null;
          updated_at: string;
          trigger: string;
        };
        Insert: {
          id?: string;
          source: string;
          watchlist_id?: string | null;
          status?: string;
          items_requested?: number;
          items_done?: number;
          items_failed?: number;
          cost_estimate_usd?: number | null;
          spend_cap_usd: number;
          cost_actual_usd?: number;
          pause_requested?: boolean;
          worker_run_id?: string | null;
          error?: string | null;
          created_by?: string | null;
          created_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          updated_at?: string;
          trigger?: string;
        };
        Update: {
          id?: string;
          source?: string;
          watchlist_id?: string | null;
          status?: string;
          items_requested?: number;
          items_done?: number;
          items_failed?: number;
          cost_estimate_usd?: number | null;
          spend_cap_usd?: number;
          cost_actual_usd?: number;
          pause_requested?: boolean;
          worker_run_id?: string | null;
          error?: string | null;
          created_by?: string | null;
          created_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          updated_at?: string;
          trigger?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'runs_watchlist_id_fkey';
            columns: ['watchlist_id'];
            isOneToOne: false;
            referencedRelation: 'watchlists';
            referencedColumns: ['id'];
          },
        ];
      };
      scores: {
        Row: {
          item_id: string;
          cohort_key: string;
          percentile: number;
          is_top: boolean;
          computed_at: string;
        };
        Insert: {
          item_id: string;
          cohort_key: string;
          percentile: number;
          is_top: boolean;
          computed_at?: string;
        };
        Update: {
          item_id?: string;
          cohort_key?: string;
          percentile?: number;
          is_top?: boolean;
          computed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'scores_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'items';
            referencedColumns: ['id'];
          },
        ];
      };
      team_members: {
        Row: {
          email: string;
          display_name: string | null;
          added_at: string;
        };
        Insert: {
          email: string;
          display_name?: string | null;
          added_at?: string;
        };
        Update: {
          email?: string;
          display_name?: string | null;
          added_at?: string;
        };
        Relationships: [];
      };
      watchlists: {
        Row: {
          id: string;
          name: string;
          type: string;
          value: string;
          source: string;
          region: string | null;
          objective: string | null;
          active: boolean;
          refresh_cadence: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          max_items: number;
          last_swept_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          value: string;
          source: string;
          region?: string | null;
          objective?: string | null;
          active?: boolean;
          refresh_cadence?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          max_items?: number;
          last_swept_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          value?: string;
          source?: string;
          region?: string | null;
          objective?: string | null;
          active?: boolean;
          refresh_cadence?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          max_items?: number;
          last_swept_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_team_member: { Args: Record<PropertyKey, never>; Returns: boolean };
      month_spend_usd: { Args: Record<PropertyKey, never>; Returns: number };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicTables = Database['public']['Tables'];
export type Tables<T extends keyof PublicTables> = PublicTables[T]['Row'];
export type TablesInsert<T extends keyof PublicTables> = PublicTables[T]['Insert'];
export type TablesUpdate<T extends keyof PublicTables> = PublicTables[T]['Update'];
